# Generated by Django 4.2.5 on 2023-10-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="link",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
