# Generated by Django 4.2.5 on 2023-10-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0003_fotografia_publicada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="link",
            field=models.ImageField(blank=True, upload_to="fotos/%Y/%m/%d/"),
        ),
    ]
