# Generated by Django 4.2.5 on 2023-10-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0004_alter_fotografia_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="foto",
            field=models.ImageField(blank=True, upload_to="fotos/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="fotografia",
            name="link",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
